#!/bin/sh -
# SPDX-License-Identifier: 0BSD
# Copyright 2021 Alexander Kozhevnikov <mentalisttraceur@gmail.com>

initialize()
{
    unused=`git log -n1` || exit 1
    branch=`git branch --show-current` || exit 1
    case $branch in '') error_not_on_branch; exit 1; esac
    root=`git rev-parse --show-toplevel` || exit 1
    cd "$root" || exit 1
    case `git rev-parse --git-common-dir` in .git) :;; *)
        error_missing_git_directory; exit 1
    esac
    git diff --staged --quiet
    case $? in 1)
        had_staged_changes=true || exit 1
        git commit --quiet --message 'git-cotree temporary commit' || exit 1
    esac
    git diff --quiet
    case $? in 1)
        had_unstaged_changes=true || exit 1
        git stash --all --quiet || exit 1
    esac
    git rm -r --force --quiet --ignore-unmatch . || exit 1
    git config --local core.bare true || exit 1
    directory=`mktemp -d git-cotree-XXXXXX` || exit 1
    git worktree add --quiet "$directory" "$branch" || exit 1
    cd "$directory" || exit 1
    case $had_staged_changes in true)
        git reset --quiet HEAD~1 || exit 1
        git add --all || exit 1
    esac
    case $had_unstaged_changes in true)
        git stash pop --quiet || exit 1
    esac
    cd "$root" || exit 1
    case $branch in ?*/*)
        mkdir -p "${branch%/*}" || exit 1
    esac
    git worktree move "$directory" "$branch" || exit 1
    git worktree lock --reason 'co-tree base branch' "$branch" || exit 1
}

create()
{
    case $# in 0) error_need_co_tree; exit 1; esac
    directory=${1%/} || exit 1
    root=`git rev-parse --git-common-dir`/.. || exit 1
    root=`cd "$root" && pwd` || exit 1
    case $# in 1)
        exec 3>&1
        unused=`git worktree add "$root/$directory" "$directory" 2>&1 1>&3` \
        || git worktree add "$root/$directory" -b "$directory" \
        || exit 1
        exit 0
    esac
    git worktree add "$root/$directory" -b "$directory" "$2" || exit 1
}

delete()
{
    case $# in 0) error_need_co_tree; exit 1; esac
    directory=${1%/} || exit 1
    root=`git rev-parse --git-common-dir`/.. || exit 1
    root=`cd "$root" && pwd` || exit 1
    git worktree remove $force "$root/$directory" || exit 1
    if git show-ref --verify --quiet refs/heads/"$directory"
    then
        git branch --delete $force "$directory" || exit 1
    fi
    while :
    do
        case $directory in */*)
            directory=${directory%/*} || exit 1
            rmdir "$root/$directory" || exit 0
            continue
        esac
        break
    done
}

base()
{
    case $# in 0) error_need_co_tree; exit 1; esac
    directory=${1%/} || exit 1
    root=`git rev-parse --git-common-dir`/.. || exit 1
    cd "$root" || exit 1
    ref=refs/heads/$directory
    if git show-ref --verify --quiet "$ref"
    then
        previous=`git branch --show-current` || exit 1
        git worktree lock --reason 'co-tree base branch' "$directory" || exit 1
        printf '%s\n' "ref: $ref" >.git/HEAD || exit 1
        if test x"$previous" != x"$directory"
        then
            git worktree unlock "$previous" || exit 1
        fi
        exit 0
    fi
    error_not_a_branch "$directory"; exit 1
}

error_not_on_branch()
{
    printf '%s\n' 'must be on a branch' 1>&2
}

error_missing_git_directory()
{
    printf '%s\n' 'missing .git directory' 1>&2
}

error_not_a_branch()
{
    printf '%s\n' "not a branch: $1" 1>&2
}

error_need_co_tree()
{
    printf '%s\n' 'need co-tree argument' 1>&2
}

bad_option()
{
    printf '%s\n' "bad option: $1" 1>&2
}

help()
{
    printf '%s' \
'Usage:
    git-cotree <co-tree> [<commit-ish>]
    git-cotree --delete [--force] <co-tree>
    git-cotree --initialize
    git-cotree --base <co-tree>

Options:
    -h --help --usage       show this help text
    -i --init --initialize  set up for using co-trees
    -d --delete             delete this co-tree
    -f --force              force deleting this co-tree
    -D                      short for both --delete and --force
    -b --base               use this co-tree as the base branch
' || exit 1
}

force=
action=create
for argument
do
    case $argument in
    -h | --help | --usage) help; exit $?;;
    -i | --init | --initialize) action=initialize || exit 1;;
    -b | --base) action=base || exit 1;;
    -d | --delete) action=delete || exit 1;;
    -f | --force) force=--force || exit 1;;
    -fd | -df | -D) force=--force && action=delete || exit 1;;
    -*) bad_option "$1"; exit 1;;
    *) break;;
    esac
    shift 1
done
"$action" "$@"
