#!/bin/sh -
# SPDX-License-Identifier: 0BSD
# Copyright 2021 Alexander Kozhevnikov <mentalisttraceur@gmail.com>
unused=`git log -n1` || exit 1
branch=`git branch --show-current` || exit 1
root=`git rev-parse --show-toplevel` || exit 1
cd "$root" || exit 1
git diff --quiet
case $? in 1)
    stashed=true || exit 1
    git stash --quiet || exit 1
esac
git rm -r --force --quiet --ignore-unmatch . || exit 1
git config --local core.bare true || exit 1
git worktree add --quiet "$branch" "$branch" || exit 1
for untracked_file in * .*
do
    case $untracked_file in "$branch" | .. | . | .git) :;; *)
        mv "$untracked_file" "$branch"/ || exit 1
    esac
done
cd "$branch" || exit 1
case $stashed in true)
    git stash pop --quiet || exit 1
esac
